builds:
  - id: "lazymonty"
    main: ./cmd/lazymonty
    binary: "lazymonty"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
  - id: "normalmonty"
    main: ./cmd/normalmonty
    binary: "normalmonty"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
