builds:
  - id: "lazymonty"
    main: ./cmd/lazymonty
    binary: "lazymonty"
    env:
      - CGO_ENABLED=0
  - id: "normalmonty"
    main: ./cmd/normalmonty
    binary: "normalmonty"
    env:
      - CGO_ENABLED=0
